<?php

  function clock_angle_menu(){
      $items['clock_angle'] = array(
          'title' => 'Clock Angle Calculator',
          'page callback' => 'drupal_get_form',
          'page arguments' => array('clock_input_form'),
          'access callback' => TRUE,
          'type' => MENU_NORMAL_ITEM,
      );
      $items['display_clock_angle'] = array(
          'title' => 'Clock Angel Results',
          'page callback' => 'clock_angle_results',
          'access callback' => TRUE,
          'type' => MENU_CALLBACK,
      );
    return $items;
  }

  function clock_input_form(){
      $form['hour_input'] = array(
          '#title' => 'Hour Input',
          '#type' => 'textfield',
          '#element_validate' => array('element_validate_number', 'element_validate_hour'),
          '#description' => t('Please input an hour between 1-12'),
          '#required' => TRUE,
      );
      $form['minute_input'] = array(
          '#title' => 'Minute Input',
          '#type' => 'textfield',
          '#element_validate' => array('element_validate_number', 'element_validate_minute'),
          '#description' => t('Please input a minute between 0-59'),
          '#required' => TRUE,
      );
      $form['submit'] = array(
          '#type' => 'submit',
          '#value' => 'Enter'
      );
      return $form;
  }

  function element_validate_hour($element) {
    if($element['#value'] < 1 || $element['#value'] > 12){
      form_error($element, t('choose from 1-12'));
    }
  }

  function element_validate_minute($element) {
    if($element['#value'] < 0 || $element['#value'] > 59){
      form_error($element, t('choose from 0-59'));
    }
  }

  function clock_input_form_submit($form, &$form_state) {
    $hour = $form_state['values']['hour_input'];
    $minute = $form_state['values']['minute_input'];

    if($hour == 12){$hour = 0;}

    $hour_degree = (30 * $hour) + (0.5 * $minute);
    $minute_degree = 6 * $minute;
    $distance_degree = abs($hour_degree - $minute_degree);
    if($distance_degree > 180){
      $distance_degree = 360 - $distance_degree;
    }
    $_SESSION['clock_angle'] = $distance_degree;
    $form_state['redirect'] = 'display_clock_angle';
  }

  function clock_angle_results() {
    $distance_degree = $_SESSION['clock_angle'];

    return "The number of degrees between the minute hand and the hour hand are " . $distance_degree . "! Good Job!";
  }
